# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/VGA_ctrl_project.xdc

# IP: C:/Users/sarah/OneDrive/Dokumente/FH/5. Sem/CHIP/Froeler_Project/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc8051_ram || ORIG_REF_NAME==mc8051_ram}]
