# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sarah/OneDrive/Dokumente/FH/5. Sem/CHIP/Froeler_Project/impl/VGA_controller_project/VGA_controller_project.srcs/sources_1/ip/rom2/rom2.xci
# IP: The module: 'rom2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sarah/OneDrive/Dokumente/FH/5. Sem/CHIP/Froeler_Project/impl/VGA_controller_project/VGA_controller_project.srcs/sources_1/ip/rom2/rom2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/sarah/OneDrive/Dokumente/FH/5. Sem/CHIP/Froeler_Project/impl/VGA_controller_project/VGA_controller_project.srcs/sources_1/ip/rom2/rom2.xci
# IP: The module: 'rom2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sarah/OneDrive/Dokumente/FH/5. Sem/CHIP/Froeler_Project/impl/VGA_controller_project/VGA_controller_project.srcs/sources_1/ip/rom2/rom2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
